### ISSUE TITLE
서울시범죄데이터 분석

### ISSUE THREAD

**Issue by choi-jonghwan-salgabda** [team-no-1/seoul-crime-analysis#1]
## Description
서울시 범죄데이터를 분석하여 학습에 알맞은 데이터로 정리한다.
## Tasks
- [ ] 데이터 규모확인
- [ ] 변수 개수등의 정보 확인
- [ ] 데이터 TYPE정보 분석
- [ ] 컬럼별 사분위 자료 정보분석
- [ ] 특정 카테고리별 특성 분석
- [ ] 임의으 row정보 확인
- [ ] 결측치 확인-결측치가 있는 데이타들의 특징 분석
- [ ] 0보다 작은값이 있는 그룹 분석
- [ ] 데이타의 시각화
- [ ] 변수간의 관계분석
- [ ] 표준화를 해본다
- [ ] 정규화를 해본다.
## References
온라인 학습 강의안 참조, statics교안 참조
