### ISSUE TITLE
2021 서울 5대범죄 분석 지도

### ISSUE THREAD

**Issue by ysyou1082** [team-no-1/seoul-crime-analysis#5]
## Description
2021 서울시 지역(구)별 5대 범죄율 시각화

## Tasks
- [x] data load : 2021 서울 범죄 데이터 csv 파일 불러오고 불필요한 컬럼 및 행 삭제
- [x] data merging : 범죄 데이터와 인구 데이터 병합
- [x] data analyzing : 발생 건수 대비 검거율 계산, 데이터 정규화, 인구 대비 범죄 비율 계산
- [x] data visualizing : 전체 발생 비율로 히트맵 생성, 살인 발생 건수 기준 지도 출력
